- name: Demo on Play vars
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
       ansible.builtin.debug:
         msg: URL == {{ URL }}

## In ansibel we access variable with two flower braces . {{URL}} , {{ URL }} ,that spacing helps in reading the code better way .
# play variable declare on play means all tasks can access that variable
# note : variable of on play cannot be accessed by another play 