- name: Loop
  hosts: all
  tasks:
    - name: Fruit name
      ansible.builtin.debug:
        msg: Fruit Name = {{ item }}
      loop:
        - banana
        - apple
        - orange
    - name: Fruit name with Quantity
      ansible.builtin.debug:
        msg: Fruit Name = {{ item.name }}, Quantity = {{ item.qty }}
      loop:
        - { name: banana, qty: 100 }
        - { name: apple, qty: 200 }
    - name: Place the result of the current item in the variable
      ansible.builtin.shell: echo "{{ item }}"
      loop:
        - one
        - two
      register: echo
      changed_when: echo.stdout != "one"