- name: read ssm parameter
  hosts: local hosts
  tasks:
    - - name: Install botocore and boto3
        ansible.builtin.pip:
          name: "{{item}}"
          executable: pip3.3
        loop:
          - botocore
          - boto3

    - name: lookup ssm parameter store in the current region
      debug: msg="{{ lookup('aws_ssm', 'mutable.cart.dev.CATALOGUE_HOST', region='us-east-1' ) }}"